### ISSUE TITLE
runtime error, what could cause please

### ISSUE THREAD

**Issue by horllste** [subTee/PoshRat#2]
Exception calling "GetBytes" with "1" argument(s): "Array cannot be null.
Parameter name: chars"
At C:\Users\root\Desktop\PoshRat-master\PoshRatHTTP.ps1:92 char:61
+     [byte[]] $buffer = [System.Text.Encoding]::UTF8.GetBytes <<<< ($message)
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException

Property 'ContentLength64' cannot be found on this object; make sure it exists and is settable.
At C:\Users\root\Desktop\PoshRat-master\PoshRatHTTP.ps1:93 char:15
+     $response. <<<< ContentLength64 = $buffer.length
    + CategoryInfo          : InvalidOperation: (ContentLength64:String) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

You cannot call a method on a null-valued expression.
At C:\Users\root\Desktop\PoshRat-master\PoshRatHTTP.ps1:95 char:18
+     $output.Write <<<< ($buffer, 0, $buffer.length)
    + CategoryInfo          : InvalidOperation: (Write:String) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\root\Desktop\PoshRat-master\PoshRatHTTP.ps1:96 char:18
+     $output.Close <<<< ()
    + CategoryInfo          : InvalidOperation: (Close:String) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Exception calling "GetContext" with "0" argument(s): "Cannot access a disposed object.
Object name: 'System.Net.HttpListener'."
At C:\Users\root\Desktop\PoshRat-master\PoshRatHTTP.ps1:38 char:36
+     $context = $listener.GetContext <<<< () # blocks until request is received
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException

Exception calling "GetBytes" with "1" argument(s): "Array cannot be null.
Parameter name: chars"
At C:\Users\root\Desktop\PoshRat-master\PoshRatHTTP.ps1:92 char:61
+     [byte[]] $buffer = [System.Text.Encoding]::UTF8.GetBytes <<<< ($message)
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException

Property 'ContentLength64' cannot be found on this object; make sure it exists and is settable.
At C:\Users\root\Desktop\PoshRat-master\PoshRatHTTP.ps1:93 char:15
+     $response. <<<< ContentLength64 = $buffer.length
    + CategoryInfo          : InvalidOperation: (ContentLength64:String) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

**Comment by subTee** [comment]
Are you running as Admin?  This server script requires admin rights.
